import { Component } from "@angular/core";
import { areAnagrams2 } from "./anag";
import { isPalindrome } from "./palin";
import { repeatedItem } from "./repeatedItemSearch";
import { repeatedItemLoops } from "./repeatedItemSearch";
import { compare } from "./compareItems";
import { compareMatrixTest } from "./compareItemMatrix";
import { sortMethod } from "./sort";
import { fizzBuzzItem } from "./fizzBuzz";
import { atoiItemTest } from "./atoi";
import { randomIntTest } from "./randomItem";
import { testShuffle } from "./shuffleItem";
import { testStack } from "./stackItem";
import { testQueue } from "./queue";
import { testQueueOptimized } from "./queue-optimized";
import { testLinkedListNode } from "./linkedListNodeItem";
import { testDoublyLinkedListNode } from "./doublyLinkedListItem";
import { testSingletonAlgo } from "./singleton";
import { testProductFactory } from "./factory";
import { testProductBuilder } from "./builder";
import { testHighWord } from "./stringHighWord";
import { testStringArrayWordsOrder } from "./stringArrayWordsOrder";

export function initTestItem() {
  // console.log(areAnagrams2("TEst", "test"));
  // console.log(areAnagrams2("TEst", "testd"));
  // console.log(areAnagrams2("earth", "heart"));
  console.log(isPalindrome("mAdam"));
  // console.log(isPalindrome("TEst"));
  // console.log(repeatedItemLoops([1, 2, 3]));
  // console.log(repeatedItemLoops([1, 2, 2]));
  // console.log(repeatedItem([1, 2, 3]));
  // console.log(repeatedItem([1, 2, 2]));
  // compare();
  // compareMatrixTest();
  // sortMethod();
  // fizzBuzzItem();
  // randomIntTest();
  // testShuffle();
  // testStack();
  // testQueue();
  // testQueueOptimized();
  // testDoublyLinkedListNode();
  // testSingletonAlgo();
  // testProductFactory();
  // testProductBuilder();
  // testHighWord();
  // testStringArrayWordsOrder();
}
